### ISSUE TITLE
What are the 4 required variables?

### ISSUE THREAD

**Issue by damusix** [azavea/terraform-aws-ecs-cluster#32]
<img width="464" alt="screen shot 2018-06-13 at 4 58 35 pm" src="https://user-images.githubusercontent.com/4218587/41378077-f4c4a7ce-6f2b-11e8-8e6b-9f4345e39a3b.png">

Documentation for this module is not the best

**Comment by damusix** [comment]
terraform just answered my question:

```
Error: module "ecs-cluster": missing required argument "key_name"
Error: module "ecs-cluster": missing required argument "cloud_config_content"
Error: module "ecs-cluster": missing required argument "private_subnet_ids"
Error: module "ecs-cluster": missing required argument "vpc_id"
```

**Comment by rbreslow** [comment]
Hey @damusix, thanks for raising this!

**Provision Instructions** is generated by the Terraform module registry:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1774125/41378518-45735ac0-6f2d-11e8-8352-0d92b09ec356.png">

You can check out our [README](https://github.com/azavea/terraform-aws-ecs-cluster/blob/develop/README.md) or view documentation on the [Terraform module registry](https://registry.terraform.io/modules/azavea/ecs-cluster/aws/1.1.0).
