### ISSUE TITLE
ecs-agent failing to register with cluster

### ISSUE THREAD

**Issue by echeipesh** [azavea/terraform-aws-ecs-cluster#36]
I'm seeing EC2 instance failing to register with the ECS cluster. Log inspection reveals this:

```
2018-08-22T15:56:10Z [INFO] Loading configuration
2018-08-22T15:56:10Z [INFO] Amazon ECS agent Version: 1.20.1, Commit: 02a6a9ff
2018-08-22T15:56:10Z [INFO] Creating root ecs cgroup: /ecs
2018-08-22T15:56:10Z [INFO] Creating cgroup /ecs
2018-08-22T15:56:10Z [INFO] Loading state! module="statemanager"
2018-08-22T15:56:10Z [INFO] Event stream ContainerChange start listening...
2018-08-22T15:56:10Z [INFO] Registering Instance with ECS
2018-08-22T15:56:30Z [ERROR] Could not register: RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2018-08-22T15:56:30Z [ERROR] Error registering: RequestError: send request failed
```

Modifying outbound rules on the `sgContainerInstance` security group to allow all outbound TCP connections resolves the problem.

Since this security group is created by the module I'm unclear on how to resolve this and why its not a more common problem. What is the correct course of action here?

Reference usage: https://github.com/moradology/osmesa/blob/feature/stream-on-ecs/deployment/streaming/terraform/container_cluster.tf

**Comment by hectcastro** [comment]
The approach we usually take looks like:

```tcl
resource "aws_security_group_rule" "container_instance_http_egress" {
  type        = "egress"
  from_port   = 80
  to_port     = 80
  protocol    = "tcp"
  cidr_blocks = ["0.0.0.0/0"]

  security_group_id = "${module.container_service_cluster.container_instance_security_group_id}"
}
```

Basically, we use the module's `container_instance_security_group_id` output to create all of the `aws_security_group_rule` resources necessary.

See also: https://github.com/geotrellis/geotrellis-site-deployment/

---

I think that we can take the following steps to make this clearer:

- Add the creation of a `aws_security_group_rule` to the example in the `README`
- Add a note to the `README` that makes the expected usage clearer

**Comment by spaszek** [comment]
Pardon me for asking, as I am not an AWS expert, but is the provided solution secure and in line with best practices?

Shouldn't this be somehow implicitly assumed from underlying AmazonEC2ContainerServiceRole? Why is it really necessary to explicitly open outbound traffic?

**Comment by tomaszdudek7** [comment]
@hectcastro 
Pardon me for asking, as I am not an AWS expert, but is the provided solution secure and in line with best practices?

Shouldn't this be somehow implicitly assumed from underlying AmazonEC2ContainerServiceRole? Why is it really necessary to explicitly open outbound traffic?

**Comment by hectcastro** [comment]
I believe that egress over HTTPS is necessary for the `ecs-agent` (a service running on the underlying EC2 nodes that are members of the ECS cluster) to communicate with the Amazon ECS service endpoint (the public ECS API).

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/get-set-up-for-amazon-ecs.html#create-a-base-security-group

It may be possible to circumvent some of this by using VPC Endpoints to talk to ECS from within a VPC using only private IP addresses via PrivateLink, but that isn't something I've done myself.

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/vpc-endpoints.html

**Comment by tomaszdudek7** [comment]
@hectcastro Whoops, seemingly I did not notice that part of the documentation. Thanks for a quick answer!
