### ISSUE TITLE
Generalize naming for variable to supply subnets

### ISSUE THREAD

**Issue by joseguerrero** [azavea/terraform-aws-ecs-cluster#38]
Is there a reason for not being able to select a list of public subnets instead of the private ones?

Thanks!

**Comment by hectcastro** [comment]
Hm. This may just be an artifact of how we do things. I'm not sure that anything would break if you provided a list of public vs. private subnet IDs for the `private_subnet_ids` variable.

Have you tried and it didn't work?

**Comment by joseguerrero** [comment]
Hi, yes you are right, I tried a public subnet on it and it works flawlessly. Maybe updating the docs here and in the terraform registry would help to avoid this confusion.

**Comment by hectcastro** [comment]
Makes sense.

We should update the variable naming so that it reflects that private or public subnets can be supplied to the ECS cluster configuration.
