### ISSUE TITLE
aws_ami ecs_ami is missing owners required field

### ISSUE THREAD

**Issue by chris-verclytte** [azavea/terraform-aws-ecs-cluster#45]
Current configuration returns an error when applying
Error: module.container_service_cluster.data.aws_ami.ecs_ami: "owners": required field is not set

As documented in [Terraform docs](https://www.terraform.io/docs/providers/aws/d/ami.html#owners), owners seems to be a required field.

**Comment by hectcastro** [comment]
Hey @chris-verclytte, what version of Terraform and the Terraform AWS provider are you on? We haven't run into this yet, but it may be related to a newer version of Terraform or the AWS provider.

**Comment by chris-verclytte** [comment]
Hi @hectcastro, I am currently using terraform v0.11.13 and aws provider v2.7.

**Comment by hectcastro** [comment]
Interesting. It looks like this was made mandatory on the v2.0.0 release of the AWS provider: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#200-february-27-2019.
