### ISSUE TITLE
Make compatible with Terraform 0.12

### ISSUE THREAD

**Issue by hectcastro** [azavea/terraform-aws-ecs-cluster#54]
This module isn't currently compatible with Terraform 0.12. The [0.12 upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html) outlines backwards incompatible changes that need to be made.

Consider using https://github.com/azavea/terraform-aws-ecs-cluster/pull/53 as a starting point.

**Comment by rbreslow** [comment]
Bouncing this to `in review` while we wait for the opportunity to test in https://github.com/azavea/raster-foundry-platform/issues/1041.

See: https://github.com/azavea/terraform-aws-ecs-cluster/tree/feature/jrb/terraform-0.12

**Comment by nanotubing** [comment]
implemented in #56
