### ISSUE TITLE
Set name prefix for Container Instance Launch Configuration

### ISSUE THREAD

**Issue by tnation14** [azavea/terraform-aws-ecs-cluster#7]
Allow users to set the `name_prefix` field for `aws_launch_configuration.container_instance`. The prefix will be pre-pended to the Terraform-generated Launch Configuration name, as seen in https://github.com/azavea/isprs-potsdam-viz/pull/13. This will allow us to automatically update/destroy named Launch Configurations without detaching them from the assigned AutoScaling group.

**Comment by hectcastro** [comment]
Resolved by https://github.com/azavea/terraform-aws-ecs-cluster/pull/8
