### ISSUE TITLE
Typo in readme and strange error

### ISSUE THREAD

**Issue by bizmate** [azavea/terraform-aws-ecs-cluster#9]
Some of the parameters mentioned in the README are apparently not valid
```
$ terraform plan
1 error(s) occurred:

* module root: 
    module container_service_cluster: root_block_device_type is not a valid parameter
    module container_service_cluster: root_block_device_size is not a valid parameter
```

Also a quote is missing here https://github.com/azavea/terraform-aws-ecs-cluster/blame/develop/README.md#L26

Any idea why the params error is shown?

**Comment by bizmate** [comment]
easy enough https://github.com/azavea/terraform-aws-ecs-cluster/pull/10

**Comment by hectcastro** [comment]
Resolved by https://github.com/azavea/terraform-aws-ecs-cluster/pull/10
